// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace BackendTp.Data.Models;

public partial class Comprobante
{
    public int IdComprobante { get; set; }

    public int IdCompra { get; set; }

    public DateTime FechaEmision { get; set; }

    public decimal Total { get; set; }

    public int IdFormaPago { get; set; }

    public int IdCliente { get; set; }

    public int IdPelicula { get; set; }

    public int IdSala { get; set; }

    public int IdFuncion { get; set; }

    public virtual ICollection<DetallesComprobante> DetallesComprobantes { get; set; } = new List<DetallesComprobante>();

    public virtual Cliente IdClienteNavigation { get; set; }

    public virtual Compra IdCompraNavigation { get; set; }

    public virtual FormasPago IdFormaPagoNavigation { get; set; }

    public virtual Funcione IdFuncionNavigation { get; set; }

    public virtual Pelicula IdPeliculaNavigation { get; set; }

    public virtual Sala IdSalaNavigation { get; set; }
}