// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace BackendTp.Data.Models;

public partial class Compra
{
    public int IdCompra { get; set; }

    public DateTime FechaCompra { get; set; }

    public decimal MontoTotal { get; set; }

    public int? IdCliente { get; set; }

    public int? IdFormaPago { get; set; }

    public virtual ICollection<Comprobante> Comprobantes { get; set; } = new List<Comprobante>();

    public virtual ICollection<Entrada> Entrada { get; set; } = new List<Entrada>();

    public virtual Cliente IdClienteNavigation { get; set; }

    public virtual FormasPago IdFormaPagoNavigation { get; set; }
}