// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace BackendTp.Data.Models;

public partial class DetallesComprobante
{
    public int IdDetalle { get; set; }

    public int? IdComprobante { get; set; }

    public int? IdEntrada { get; set; }

    public decimal? Precio { get; set; }

    public virtual Comprobante IdComprobanteNavigation { get; set; }

    public virtual Entrada IdEntradaNavigation { get; set; }
}