// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace BackendTp.Data.Models;

public partial class Entrada
{
    public int IdEntrada { get; set; }

    public int Precio { get; set; }

    public int? IdCompra { get; set; }

    public int? IdFuncion { get; set; }

    public int? IdButaca { get; set; }

    public virtual ICollection<DetallesComprobante> DetallesComprobantes { get; set; } = new List<DetallesComprobante>();

    public virtual Butaca IdButacaNavigation { get; set; }

    public virtual Compra IdCompraNavigation { get; set; }

    public virtual Funcione IdFuncionNavigation { get; set; }

    public virtual ICollection<Ticket> Tickets { get; set; } = new List<Ticket>();
}