// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace BackendTp.Data.Models;

public partial class FormasPago
{
    public int IdFormaPago { get; set; }

    public string Descripcion { get; set; }

    public virtual ICollection<Compra> Compras { get; set; } = new List<Compra>();

    public virtual ICollection<Comprobante> Comprobantes { get; set; } = new List<Comprobante>();
}