// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace BackendTp.Data.Models;

public partial class Promocione
{
    public int IdPromocion { get; set; }

    public string Descrpcion { get; set; }

    public int? Descuento { get; set; }

    public DateTime? FechaInicio { get; set; }

    public DateTime? FechaFin { get; set; }

    public virtual ICollection<Funcione> Funciones { get; set; } = new List<Funcione>();
}