// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace BackendTp.Data.Models;

public partial class Reserva
{
    public int IdReserva { get; set; }

    public int IdCliente { get; set; }

    public int IdFuncion { get; set; }

    public int IdButaca { get; set; }

    public DateTime FechaReserva { get; set; }

    public string Estado { get; set; }

    public virtual Butaca IdButacaNavigation { get; set; }

    public virtual Cliente IdClienteNavigation { get; set; }

    public virtual Funcione IdFuncionNavigation { get; set; }
}