// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace BackendTp.Data.Models;

public partial class Sala
{
    public int IdSala { get; set; }

    public string Nombre { get; set; }

    public int? IdTipoSala { get; set; }

    public int? Capacidad { get; set; }

    public virtual ICollection<Butaca> Butacas { get; set; } = new List<Butaca>();

    public virtual ICollection<Comprobante> Comprobantes { get; set; } = new List<Comprobante>();

    public virtual ICollection<Funcione> Funciones { get; set; } = new List<Funcione>();

    public virtual TipoSala IdTipoSalaNavigation { get; set; }

    public virtual ICollection<Ticket> Tickets { get; set; } = new List<Ticket>();
}