// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace BackendTp.Data.Models;

public partial class Ticket
{
    public int IdTicket { get; set; }

    public int? IdEntrada { get; set; }

    public int? IdPelicula { get; set; }

    public int? IdFuncion { get; set; }

    public int? IdSala { get; set; }

    public int? IdButaca { get; set; }

    public DateTime? FechaFuncion { get; set; }

    public virtual Butaca IdButacaNavigation { get; set; }

    public virtual Entrada IdEntradaNavigation { get; set; }

    public virtual Funcione IdFuncionNavigation { get; set; }

    public virtual Pelicula IdPeliculaNavigation { get; set; }

    public virtual Sala IdSalaNavigation { get; set; }
}